import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wW-AAABABAIaDFnKgqIBDACXDAIACAGOAYEAxevA4NsMAAJAMAEAAABABAJwyvFBAAgrABCABWAhHHIgvSABEggDZEAg_g3DTBguODACAcJIGIGg_fgkFLIg1JVBaEZGDLGhPhIg2gyMgyGFn_gn4NjXjEBIgvhDLJDB');
