import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wYgAEAAAAEDMAGABgiBHPRglABIAAAABgnCBARCEDAIAAAAABeKCOBDAABCBFhJgghVEBAAJAAJAADBAg2JEBBBACADw9IAXhYNghAA4I-Ugx2JNENDAEACJDiQAAACCABAABAbBlRggAAoLCAQLC4NmrhD');
