import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('JAhxAgvAwTbAgyAukBwTzBiuAgnAhJAEAg3BRAh2BsUAidAp-AhpChGBicBBAAAgoBtTBADjZEg9Bt_GACEAABSAgtAADACwyZCBAhvAicHAAAAPDBBABGCABAHAAAAmwA3T8BkMAAAjiEnVBhdBiWCiSCiPBj4A1UTCqbAgvAwSFAjGAkvHiXFhCGwUGBh0Dh9DiABAATChXBABhrAmgDLAllBEOhoBj4CsBDhUCDBmdEwgpE0X4BiEAhACJAtRB04FAx3mD');
