import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wYiDAAAAEDUAgnCACPRglABIAAAABBAAXBfADEDAIAAAAABAcAKCOBDAABCBjFAEBAAJARAABg-CAABBFA4QIKAAAABCEJACABAJAiQAACCABAABAAWDl0AoPAfA');
